# Generated by Django 3.2.12 on 2024-01-10 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_rename_assignner_task_assigner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
